name: EntityFlingerTest
version: '${project.version}'
main: com.github.groomon.entityflingertest.EntityFlingerTest
api-version: 1.16
authors: [ Groomon ]
commands:
  fling:
    description: Flings an entity
    usage: /fling [height/"nice"] [acceleration drag inertia]
  sz:
    description: Spawns an slippery zombie on top of block
    usage: /sz
  offset:
    description: Toggle offset
    usage: /offset

